name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Contract
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Install Dependencies
        run: yarn install

      - name: Test Contract
        run: yarn run hardhat:test
